'use strict';
const { DatabaseSync } = require('node:sqlite');
const path = require('path');

const DB_PATH = path.join(__dirname, 'database_enriched', 'car_database.db');
const db = new DatabaseSync(DB_PATH);

const clean = v => (v === undefined ? null : v);

// Upsert base Renault & common engine specifications
const BASE_SPECS = [
  {
    engine_code: 'D7F',
    engine_type: '1.2 8V (60hp)',
    fuel: 'Petrol',
    displacement_cc: 1149,
    power_hp: 60,
    power_kw: 44,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio / Twingo',
    year_example: 2002,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0700 / RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0700',
    oil_capacity_with_filter_l: 3.6,
    oil_capacity_without_filter_l: 3.2,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (Yellow/Green)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.5,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK BKR6E / Bosch FR7DC+',
    spark_plug_gap_mm: '0.8-0.9 mm',
    spark_plug_interval_km: 30000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '9.6:1',
    compression_pressure_min_bar: 11.0,
    compression_pressure_max_bar: 13.5,
    compression_pressure_diff_max_bar: 1.5,
    fuel_system_type: 'Multi-Point Electronic Injection (MPI)',
    fuel_pressure_low_bar: 3.0,
    fuel_pressure_high_bar: 3.0,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.2,
    oil_pressure_2000rpm_bar: 3.0,
    idle_rpm: 750,
    valve_clearance_intake: '0.10-0.15 mm (cold)',
    valve_clearance_exhaust: '0.20-0.25 mm (cold)',
    torque_nm: 93,
    torque_rpm: 2500,
    power_rpm: 5250,
    co_idle_percent: '< 0.3%',
    hc_idle_ppm: '< 100',
    lambda: '0.97-1.03'
  },
  {
    engine_code: 'D4F',
    engine_type: '1.2 16V (75hp)',
    fuel: 'Petrol',
    displacement_cc: 1149,
    power_hp: 75,
    power_kw: 55,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio / Twingo / Modus',
    year_example: 2006,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0700 / RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0700',
    oil_capacity_with_filter_l: 4.0,
    oil_capacity_without_filter_l: 3.6,
    oil_change_interval_km: 20000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (Yellow/Green)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.2,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK LZKAR7A / Eyquem RFC58LZ2E',
    spark_plug_gap_mm: '0.9 mm',
    spark_plug_interval_km: 30000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '9.8:1',
    compression_pressure_min_bar: 11.5,
    compression_pressure_max_bar: 13.8,
    compression_pressure_diff_max_bar: 1.5,
    fuel_system_type: 'Multi-Point Electronic Injection (MPI)',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.0,
    oil_pressure_2000rpm_bar: 3.0,
    idle_rpm: 700,
    valve_clearance_intake: '0.10-0.15 mm (cold)',
    valve_clearance_exhaust: '0.20-0.25 mm (cold)',
    torque_nm: 107,
    torque_rpm: 4250,
    power_rpm: 5500,
    co_idle_percent: '< 0.2%',
    hc_idle_ppm: '< 80',
    lambda: '0.97-1.03'
  },
  {
    engine_code: 'D4Ft',
    engine_type: '1.2 TCE 100 Turbo',
    fuel: 'Petrol',
    displacement_cc: 1149,
    power_hp: 100,
    power_kw: 74,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 3 / Twingo GT / Modus',
    year_example: 2008,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0710',
    oil_capacity_with_filter_l: 4.0,
    oil_capacity_without_filter_l: 3.6,
    oil_change_interval_km: 20000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.5,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7A7 / Iridium',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '9.5:1',
    compression_pressure_min_bar: 11.0,
    compression_pressure_max_bar: 13.5,
    compression_pressure_diff_max_bar: 1.5,
    fuel_system_type: 'Turbocharged Multi-Point Injection (MPI)',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.2,
    oil_pressure_2000rpm_bar: 3.2,
    idle_rpm: 750,
    valve_clearance_intake: '0.10-0.15 mm',
    valve_clearance_exhaust: '0.20-0.25 mm',
    torque_nm: 145,
    torque_rpm: 3000,
    power_rpm: 5500,
    co_idle_percent: '< 0.2%',
    hc_idle_ppm: '< 60',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'H4Bt',
    engine_type: '0.9 TCe 90 Turbo (HR09DET)',
    fuel: 'Petrol',
    displacement_cc: 898,
    power_hp: 90,
    power_kw: 66,
    cylinders: 3,
    brand_example: 'Renault',
    model_example: 'Clio 4 / Captur / Twingo 3',
    year_example: 2014,
    oil_viscosity: '5W-40 / 5W-30',
    oil_standard: 'RN0710 / RN17',
    oil_acea: 'A3/B4 or C3',
    oil_oem_spec: 'RN0710 / RN17',
    oil_capacity_with_filter_l: 4.1,
    oil_capacity_without_filter_l: 3.8,
    oil_change_interval_km: 20000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (Yellow)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.0,
    coolant_change_interval_km: 120000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    timing_belt_interval_km: null,
    timing_belt_interval_months: null,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 80000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Iridium Laser',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 72,
    compression_ratio: '9.5:1',
    compression_pressure_min_bar: 11.5,
    compression_pressure_max_bar: 14.0,
    compression_pressure_diff_max_bar: 1.2,
    fuel_system_type: 'Turbocharged Multi-Point Injection (MPI) with Overboost',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.3,
    oil_pressure_2000rpm_bar: 3.5,
    idle_rpm: 800,
    valve_clearance_intake: 'Hydraulic / Auto adjustment',
    valve_clearance_exhaust: 'Hydraulic / Auto adjustment',
    torque_nm: 135,
    torque_rpm: 2500,
    power_rpm: 5250,
    co_idle_percent: '< 0.15%',
    hc_idle_ppm: '< 50',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'B4D',
    engine_type: '1.0 SCe 65/70/75 (SCe 3-Cylinder)',
    fuel: 'Petrol',
    displacement_cc: 999,
    power_hp: 72,
    power_kw: 53,
    cylinders: 3,
    brand_example: 'Renault',
    model_example: 'Clio 5 / Twingo 3 / Sandero',
    year_example: 2020,
    oil_viscosity: '5W-30 / 0W-20',
    oil_standard: 'RN17 / RN17 FE',
    oil_acea: 'C3 / C5',
    oil_oem_spec: 'RN17',
    oil_capacity_with_filter_l: 3.0,
    oil_capacity_without_filter_l: 2.7,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D / Glaceol Eco',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 4.8,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6 (ESP compatible)',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Iridium',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '10.5:1',
    compression_pressure_min_bar: 12.0,
    compression_pressure_max_bar: 14.5,
    compression_pressure_diff_max_bar: 1.2,
    fuel_system_type: 'Multi-Point Injection (MPI) Variable Valve Timing',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.2,
    oil_pressure_2000rpm_bar: 3.2,
    idle_rpm: 750,
    valve_clearance_intake: 'Bucket shim / Hydraulic',
    valve_clearance_exhaust: 'Bucket shim / Hydraulic',
    torque_nm: 95,
    torque_rpm: 3500,
    power_rpm: 6250,
    co_idle_percent: '< 0.1%',
    hc_idle_ppm: '< 40',
    lambda: '0.99-1.01'
  },
  {
    engine_code: 'H4D',
    engine_type: '1.0 TCe 90/100 Turbo (HR10DET)',
    fuel: 'Petrol',
    displacement_cc: 999,
    power_hp: 100,
    power_kw: 74,
    cylinders: 3,
    brand_example: 'Renault',
    model_example: 'Clio 5 / Captur 2 / Duster',
    year_example: 2021,
    oil_viscosity: '5W-30',
    oil_standard: 'RN17',
    oil_acea: 'C3',
    oil_oem_spec: 'RN17',
    oil_capacity_with_filter_l: 4.1,
    oil_capacity_without_filter_l: 3.8,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D / Glaceol Eco',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.5,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Laser Iridium',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '9.5:1',
    compression_pressure_min_bar: 11.5,
    compression_pressure_max_bar: 14.0,
    compression_pressure_diff_max_bar: 1.2,
    fuel_system_type: 'Turbocharged Multi-Point Injection (MPI) with Electronic Wastegate',
    fuel_pressure_low_bar: 3.8,
    fuel_pressure_high_bar: 3.8,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.3,
    oil_pressure_2000rpm_bar: 3.6,
    idle_rpm: 800,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 160,
    torque_rpm: 2750,
    power_rpm: 5000,
    co_idle_percent: '< 0.1%',
    hc_idle_ppm: '< 40',
    lambda: '0.99-1.01'
  },
  {
    engine_code: 'H5F',
    engine_type: '1.2 TCe 115/120/130 Direct Injection Turbo',
    fuel: 'Petrol',
    displacement_cc: 1197,
    power_hp: 120,
    power_kw: 88,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 4 / Captur 1 / Megane 3 / Kadjar',
    year_example: 2015,
    oil_viscosity: '5W-40 / 5W-30',
    oil_standard: 'RN0710 / RN17',
    oil_acea: 'A3/B4 or C3',
    oil_oem_spec: 'RN0710 / RN17',
    oil_capacity_with_filter_l: 4.6,
    oil_capacity_without_filter_l: 4.2,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 5.7,
    coolant_change_interval_km: 120000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Double Platinum',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 72,
    compression_ratio: '10.0:1',
    compression_pressure_min_bar: 12.0,
    compression_pressure_max_bar: 14.5,
    compression_pressure_diff_max_bar: 1.2,
    fuel_system_type: 'Gasoline Direct Injection (GDI / DIG-T Turbo)',
    fuel_pressure_low_bar: 4.5,
    fuel_pressure_high_bar: 150,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.4,
    oil_pressure_2000rpm_bar: 3.8,
    idle_rpm: 750,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 205,
    torque_rpm: 2000,
    power_rpm: 4900,
    co_idle_percent: '< 0.1%',
    hc_idle_ppm: '< 40',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'H5H',
    engine_type: '1.3 TCe 115/130/140/160 GPF (HR13DDT / M282)',
    fuel: 'Petrol',
    displacement_cc: 1332,
    power_hp: 140,
    power_kw: 103,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 5 / Captur 2 / Megane 4 / Kadjar / Arkana',
    year_example: 2021,
    oil_viscosity: '5W-30 / 0W-20',
    oil_standard: 'RN17 / RN17 FE',
    oil_acea: 'C3 / C5',
    oil_oem_spec: 'RN17',
    oil_capacity_with_filter_l: 5.4,
    oil_capacity_without_filter_l: 5.0,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D / Glaceol Eco',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 6.2,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6 Low Viscosity',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Laser Iridium GPF',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '10.6:1',
    compression_pressure_min_bar: 12.5,
    compression_pressure_max_bar: 15.0,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'Direct Gasoline Injection (250 bar) + Gasoline Particulate Filter (GPF)',
    fuel_pressure_low_bar: 5.0,
    fuel_pressure_high_bar: 250,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.5,
    oil_pressure_2000rpm_bar: 4.0,
    idle_rpm: 750,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 240,
    torque_rpm: 1600,
    power_rpm: 5500,
    co_idle_percent: '< 0.05%',
    hc_idle_ppm: '< 30',
    lambda: '0.99-1.01'
  },
  {
    engine_code: 'H5Ht',
    engine_type: '1.3 TCe 140/160 Mild Hybrid 12V',
    fuel: 'Hybrid',
    displacement_cc: 1332,
    power_hp: 160,
    power_kw: 118,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Austral / Arkana / Captur 2',
    year_example: 2022,
    oil_viscosity: '0W-20 / 5W-30',
    oil_standard: 'RN17 FE / RN17',
    oil_acea: 'C5 / C3',
    oil_oem_spec: 'RN17 FE',
    oil_capacity_with_filter_l: 5.4,
    oil_capacity_without_filter_l: 5.0,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D / Glaceol Eco',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 6.5,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6 Low Viscosity',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR7J7G / Iridium GPF',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '10.6:1',
    compression_pressure_min_bar: 12.5,
    compression_pressure_max_bar: 15.0,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'Direct Injection 250 bar + 12V Mild-Hybrid Starter-Generator',
    fuel_pressure_low_bar: 5.0,
    fuel_pressure_high_bar: 250,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.5,
    oil_pressure_2000rpm_bar: 4.0,
    idle_rpm: 750,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 270,
    torque_rpm: 1800,
    power_rpm: 5500,
    co_idle_percent: '< 0.05%',
    hc_idle_ppm: '< 25',
    lambda: '0.99-1.01'
  },
  {
    engine_code: 'H4M',
    engine_type: '1.6 E-Tech 140/145/160 PHEV Full Hybrid (HR16DE)',
    fuel: 'Hybrid',
    displacement_cc: 1598,
    power_hp: 145,
    power_kw: 107,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 5 E-Tech / Captur 2 E-Tech / Arkana / Megane',
    year_example: 2021,
    oil_viscosity: '0W-20 / 5W-30',
    oil_standard: 'RN17 FE / RN17',
    oil_acea: 'C5 / C3',
    oil_oem_spec: 'RN17 FE',
    oil_capacity_with_filter_l: 4.2,
    oil_capacity_without_filter_l: 3.9,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (Dual Circuit - Engine + Inverter)',
    coolant_spec: 'OAT Type D Low Conductivity',
    coolant_capacity_l: 6.8,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6 (Regenerative braking)',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK DILKAR7B8 / Double Iridium',
    spark_plug_gap_mm: '0.8 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '10.7:1',
    compression_pressure_min_bar: 12.0,
    compression_pressure_max_bar: 14.5,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'Dual Multi-Point Port Injection (MPI) Atkinson Cycle + Dual Electric Motors',
    fuel_pressure_low_bar: 3.8,
    fuel_pressure_high_bar: 3.8,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.3,
    oil_pressure_2000rpm_bar: 3.7,
    idle_rpm: 800,
    valve_clearance_intake: 'Solid lifter bucket',
    valve_clearance_exhaust: 'Solid lifter bucket',
    torque_nm: 205,
    torque_rpm: 3200,
    power_rpm: 5600,
    co_idle_percent: '< 0.05%',
    hc_idle_ppm: '< 20',
    lambda: '0.99-1.01'
  },
  {
    engine_code: 'M5M',
    engine_type: '1.6 RS 200 / Trophy 220 Turbo (MR16DDT)',
    fuel: 'Petrol',
    displacement_cc: 1618,
    power_hp: 200,
    power_kw: 147,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 4 RS / Talisman / Espace 5 / Kadjar',
    year_example: 2016,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0710',
    oil_capacity_with_filter_l: 4.5,
    oil_capacity_without_filter_l: 4.1,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 6.5,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Chain',
    air_filter_interval_km: 20000,
    air_filter_interval_months: 12,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4 High Performance / DOT 5.1',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK DILKAR8A8 / Laser Iridium RS',
    spark_plug_gap_mm: '0.8 mm',
    spark_plug_interval_km: 40000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '9.5:1',
    compression_pressure_min_bar: 11.5,
    compression_pressure_max_bar: 14.0,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'High-Pressure Direct Injection (GDI 150 bar) Turbocharged with Twin VVT',
    fuel_pressure_low_bar: 4.5,
    fuel_pressure_high_bar: 150,
    fuel_octane_requirement: '98 RON (Premium recommended)',
    oil_pressure_idle_bar: 1.4,
    oil_pressure_2000rpm_bar: 3.8,
    idle_rpm: 750,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 260,
    torque_rpm: 1750,
    power_rpm: 6050,
    co_idle_percent: '< 0.1%',
    hc_idle_ppm: '< 40',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'M5Pt',
    engine_type: '1.8 RS 280 / 300 Trophy Turbo (MR18DDT / Alpine A110)',
    fuel: 'Petrol',
    displacement_cc: 1798,
    power_hp: 300,
    power_kw: 221,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Megane 4 RS / Trophy / Alpine A110 / Espace 5',
    year_example: 2020,
    oil_viscosity: '0W-40 / 5W-40 (Castrol Edge RS)',
    oil_standard: 'RN0710 / RN0720 RS',
    oil_acea: 'A3/B4 or C3',
    oil_oem_spec: 'RN0710 RS',
    oil_capacity_with_filter_l: 4.3,
    oil_capacity_without_filter_l: 3.9,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (High Thermal Capacity)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 7.2,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Chain',
    air_filter_interval_km: 20000,
    air_filter_interval_months: 12,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4 High Performance Racing (Brembo 4-pot)',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK ILKAR8H6 / Laser Iridium Racing',
    spark_plug_gap_mm: '0.65 mm',
    spark_plug_interval_km: 40000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 100000,
    aux_belt_interval_months: 60,
    compression_ratio: '9.0:1',
    compression_pressure_min_bar: 11.0,
    compression_pressure_max_bar: 13.5,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'High-Pressure Direct Injection (GDI 200 bar) Twin-Scroll Turbo with Ball Bearings',
    fuel_pressure_low_bar: 5.0,
    fuel_pressure_high_bar: 200,
    fuel_octane_requirement: '98 RON Minimum (100 RON optimal)',
    oil_pressure_idle_bar: 1.5,
    oil_pressure_2000rpm_bar: 4.2,
    idle_rpm: 800,
    valve_clearance_intake: 'DLC coated solid lifters',
    valve_clearance_exhaust: 'Sodium-filled exhaust valves',
    torque_nm: 420,
    torque_rpm: 3200,
    power_rpm: 6000,
    co_idle_percent: '< 0.1%',
    hc_idle_ppm: '< 35',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'F4Rt',
    engine_type: '2.0 16V Turbo RS 225 / 250 / 265 / 275 Trophy',
    fuel: 'Petrol',
    displacement_cc: 1998,
    power_hp: 250,
    power_kw: 184,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Megane 2/3 RS / Laguna 2/3 GT / Espace 4',
    year_example: 2012,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0710',
    oil_capacity_with_filter_l: 5.4,
    oil_capacity_without_filter_l: 5.0,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 7.5,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 20000,
    air_filter_interval_months: 12,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4 High Performance',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK PFR7Z-TG / Platinum Double',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 40000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '8.6:1',
    compression_pressure_min_bar: 10.5,
    compression_pressure_max_bar: 13.0,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'Twin-Scroll Turbocharged Multi-Point Injection (MPI)',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '98 RON',
    oil_pressure_idle_bar: 1.4,
    oil_pressure_2000rpm_bar: 3.8,
    idle_rpm: 800,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 340,
    torque_rpm: 3000,
    power_rpm: 5500,
    co_idle_percent: '< 0.15%',
    hc_idle_ppm: '< 50',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'R9N',
    engine_type: '1.7 Blue dCi 120/150 Turbo Diesel',
    fuel: 'Diesel',
    displacement_cc: 1749,
    power_hp: 150,
    power_kw: 110,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Scenic 4 / Kadjar / Koleos 2 / Talisman',
    year_example: 2020,
    oil_viscosity: '5W-30 / 0W-20',
    oil_standard: 'RN17 / RN17 FE',
    oil_acea: 'C3 / C5 Low SAPS',
    oil_oem_spec: 'RN17',
    oil_capacity_with_filter_l: 5.5,
    oil_capacity_without_filter_l: 5.1,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D (Low-temp EGR Loop)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 7.8,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 36,
    brake_fluid_type: 'DOT 4 Class 6',
    brake_fluid_change_months: 24,
    spark_plug_type: 'N/A (BorgWarner Glow Plug 7V Quick Glow)',
    spark_plug_gap_mm: '-',
    spark_plug_interval_km: 80000,
    spark_plug_interval_months: 60,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '15.2:1',
    compression_pressure_min_bar: 24.0,
    compression_pressure_max_bar: 29.0,
    compression_pressure_diff_max_bar: 2.0,
    fuel_system_type: 'Common Rail Direct Diesel Injection (CRDi 2500 bar) + SCR AdBlue + DPF',
    fuel_pressure_low_bar: 4.5,
    fuel_pressure_high_bar: 2500,
    fuel_octane_requirement: 'Diesel EN 590 / Cetane 51+',
    oil_pressure_idle_bar: 1.6,
    oil_pressure_2000rpm_bar: 4.2,
    idle_rpm: 800,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 340,
    torque_rpm: 1750,
    power_rpm: 3500,
    co_idle_percent: '< 0.02%',
    hc_idle_ppm: '< 20',
    lambda: 'Excess air (Diesel lean)'
  },
  {
    engine_code: 'HR12',
    engine_type: '1.2 E-Tech Full Hybrid 200 / 300 4x4 (HR12DDV)',
    fuel: 'Hybrid',
    displacement_cc: 1199,
    power_hp: 200,
    power_kw: 147,
    cylinders: 3,
    brand_example: 'Renault',
    model_example: 'Austral / Espace 6 / Rafale',
    year_example: 2023,
    oil_viscosity: '0W-20',
    oil_standard: 'RN17 FE',
    oil_acea: 'C5',
    oil_oem_spec: 'RN17 FE',
    oil_capacity_with_filter_l: 4.2,
    oil_capacity_without_filter_l: 3.8,
    oil_change_interval_km: 30000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D / Glaceol Eco Dual Circuit',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 7.2,
    coolant_change_interval_km: 150000,
    coolant_change_interval_months: 60,
    timing_type: 'Chain',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 90000,
    fuel_filter_interval_months: 60,
    brake_fluid_type: 'DOT 4 Class 6 Low Viscosity',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK DILKAR7B8 / Double Iridium',
    spark_plug_gap_mm: '0.7 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 150000,
    aux_belt_interval_months: 72,
    compression_ratio: '12.0:1',
    compression_pressure_min_bar: 13.0,
    compression_pressure_max_bar: 15.5,
    compression_pressure_diff_max_bar: 1.0,
    fuel_system_type: 'Gasoline Direct Injection 350 bar + Miller Cycle + Dual Electric Motors (50kW + 25kW)',
    fuel_pressure_low_bar: 5.5,
    fuel_pressure_high_bar: 350,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.5,
    oil_pressure_2000rpm_bar: 4.2,
    idle_rpm: 850,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 410,
    torque_rpm: 1750,
    power_rpm: 4500,
    co_idle_percent: '< 0.03%',
    hc_idle_ppm: '< 20',
    lambda: '0.99-1.01'
  },
  {
    engine_code: '6AM',
    engine_type: 'Renault Electric Drive Unit (Megane E-Tech / R5 E-Tech)',
    fuel: 'Electric',
    displacement_cc: 0,
    power_hp: 220,
    power_kw: 160,
    cylinders: 0,
    brand_example: 'Renault',
    model_example: 'Megane E-Tech / Renault 5 E-Tech',
    year_example: 2023,
    oil_viscosity: '75W-80 (Reducer Drive Fluid)',
    oil_standard: 'Elf Tranself NFP 75W-80 / EV Fluid',
    oil_acea: 'GL-4+',
    oil_oem_spec: 'Renault EV Gearbox',
    oil_capacity_with_filter_l: 1.1,
    oil_capacity_without_filter_l: 1.0,
    oil_change_interval_km: 100000,
    oil_change_interval_months: 60,
    coolant_type: 'Glaceol RX Type D (Battery & Inverter Thermal Loop)',
    coolant_spec: 'Low-conductivity OAT',
    coolant_capacity_l: 8.5,
    coolant_change_interval_km: 120000,
    coolant_change_interval_months: 60,
    timing_type: 'Electric Synchronous Motor with Wound Rotor (EESM - Rare Earth Free)',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: null,
    fuel_filter_interval_months: null,
    brake_fluid_type: 'DOT 4 Class 6 Low Viscosity (One-Pedal Regen)',
    brake_fluid_change_months: 24,
    spark_plug_type: 'N/A (Pure Electric Vehicle)',
    spark_plug_gap_mm: '-',
    spark_plug_interval_km: null,
    spark_plug_interval_months: null,
    aux_belt_interval_km: null,
    aux_belt_interval_months: null,
    compression_ratio: 'N/A',
    compression_pressure_min_bar: null,
    compression_pressure_max_bar: null,
    compression_pressure_diff_max_bar: null,
    fuel_system_type: '350V / 400V Lithium-ion Battery (40kWh / 60kWh) with Inverter Drive',
    fuel_pressure_low_bar: null,
    fuel_pressure_high_bar: null,
    fuel_octane_requirement: 'CCS2 DC 130kW / Type 2 AC 22kW',
    oil_pressure_idle_bar: null,
    oil_pressure_2000rpm_bar: null,
    idle_rpm: 0,
    valve_clearance_intake: 'N/A',
    valve_clearance_exhaust: 'N/A',
    torque_nm: 300,
    torque_rpm: 100,
    power_rpm: 11000,
    co_idle_percent: '0.00% (Zero Emissions)',
    hc_idle_ppm: '0',
    lambda: 'N/A'
  },
  {
    engine_code: '5AQ',
    engine_type: 'Zoe R110 / R135 Electric (52kWh ZE 50)',
    fuel: 'Electric',
    displacement_cc: 0,
    power_hp: 135,
    power_kw: 100,
    cylinders: 0,
    brand_example: 'Renault',
    model_example: 'Zoe ZE 50',
    year_example: 2020,
    oil_viscosity: '75W-80 (Reducer Drive Fluid)',
    oil_standard: 'Elf Tranself EV',
    oil_acea: 'GL-4',
    oil_oem_spec: 'Renault EV Gearbox',
    oil_capacity_with_filter_l: 1.0,
    oil_capacity_without_filter_l: 0.9,
    oil_change_interval_km: 100000,
    oil_change_interval_months: 60,
    coolant_type: 'Glaceol RX Type D (Air cooled pack + Liquid Inverter loop)',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 4.5,
    coolant_change_interval_km: 120000,
    coolant_change_interval_months: 60,
    timing_type: 'Synchronous Electric Motor (EESM)',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 12,
    brake_fluid_type: 'DOT 4 Class 6',
    brake_fluid_change_months: 24,
    spark_plug_type: 'N/A (Pure Electric)',
    spark_plug_gap_mm: '-',
    compression_ratio: 'N/A',
    fuel_system_type: '400V 52kWh LG Chem Battery + Caméléon Charger (AC 22kW / DC 50kW)',
    fuel_octane_requirement: 'AC 22kW / DC 50kW CCS',
    oil_pressure_idle_bar: null,
    oil_pressure_2000rpm_bar: null,
    idle_rpm: 0,
    valve_clearance_intake: 'N/A',
    valve_clearance_exhaust: 'N/A',
    torque_nm: 245,
    torque_rpm: 1500,
    power_rpm: 9000,
    co_idle_percent: '0.00% (Zero Emissions)',
    hc_idle_ppm: '0',
    lambda: 'N/A'
  },
  {
    engine_code: '5AL',
    engine_type: 'Twingo E-Tech Electric (82hp / 22kWh)',
    fuel: 'Electric',
    displacement_cc: 0,
    power_hp: 82,
    power_kw: 60,
    cylinders: 0,
    brand_example: 'Renault',
    model_example: 'Twingo 3 E-Tech',
    year_example: 2021,
    oil_viscosity: '75W-80',
    oil_standard: 'Elf Tranself EV',
    oil_acea: 'GL-4',
    oil_oem_spec: 'Renault EV Gearbox',
    oil_capacity_with_filter_l: 0.9,
    oil_capacity_without_filter_l: 0.8,
    oil_change_interval_km: 100000,
    oil_change_interval_months: 60,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 4.0,
    coolant_change_interval_km: 120000,
    coolant_change_interval_months: 60,
    timing_type: 'Rear Synchronous Electric Motor',
    air_filter_interval_km: 30000,
    air_filter_interval_months: 12,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'N/A',
    spark_plug_gap_mm: '-',
    compression_ratio: 'N/A',
    fuel_system_type: '400V 21.4kWh Liquid-cooled Battery + 22kW Caméléon Charger',
    fuel_octane_requirement: 'AC Type 2 (up to 22kW)',
    oil_pressure_idle_bar: null,
    oil_pressure_2000rpm_bar: null,
    idle_rpm: 0,
    valve_clearance_intake: 'N/A',
    valve_clearance_exhaust: 'N/A',
    torque_nm: 160,
    torque_rpm: 500,
    power_rpm: 8000,
    co_idle_percent: '0.00%',
    hc_idle_ppm: '0',
    lambda: 'N/A'
  },
  {
    engine_code: '3SE',
    engine_type: 'Twizy Electric 45 / 80 (Sevcon Gen4 Drive)',
    fuel: 'Electric',
    displacement_cc: 0,
    power_hp: 17,
    power_kw: 13,
    cylinders: 0,
    brand_example: 'Renault',
    model_example: 'Twizy',
    year_example: 2018,
    oil_viscosity: '75W-80 Reducer Fluid',
    oil_standard: 'Elf Tranself TRJ 75W-80',
    oil_acea: 'GL-4',
    oil_oem_spec: 'Renault Reducer',
    oil_capacity_with_filter_l: 0.7,
    oil_capacity_without_filter_l: 0.7,
    oil_change_interval_km: 80000,
    oil_change_interval_months: 60,
    coolant_type: 'Air Cooled System',
    coolant_spec: 'Passive cooling',
    coolant_capacity_l: 0.0,
    coolant_change_interval_km: null,
    timing_type: 'Asynchronous AC Induction Motor',
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'N/A',
    compression_ratio: 'N/A',
    fuel_system_type: '58V 6.1kWh Lithium-ion Battery with Schuko Mains Charger',
    fuel_octane_requirement: '230V 10A / 16A Mains Outlet',
    oil_pressure_idle_bar: null,
    oil_pressure_2000rpm_bar: null,
    idle_rpm: 0,
    valve_clearance_intake: 'N/A',
    valve_clearance_exhaust: 'N/A',
    torque_nm: 57,
    torque_rpm: 100,
    power_rpm: 6000,
    co_idle_percent: '0.00%',
    hc_idle_ppm: '0',
    lambda: 'N/A'
  },
  {
    engine_code: 'K4J',
    engine_type: '1.4 16V (98hp)',
    fuel: 'Petrol',
    displacement_cc: 1390,
    power_hp: 98,
    power_kw: 72,
    cylinders: 4,
    brand_example: 'Renault',
    model_example: 'Clio 2/3 / Megane 1/2 / Scenic 1/2',
    year_example: 2004,
    oil_viscosity: '5W-40',
    oil_standard: 'RN0700 / RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0700',
    oil_capacity_with_filter_l: 4.8,
    oil_capacity_without_filter_l: 4.4,
    oil_change_interval_km: 20000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 6.0,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4',
    brake_fluid_change_months: 24,
    spark_plug_type: 'NGK BKR6ES / Eyquem RFC58LZ2E',
    spark_plug_gap_mm: '0.9 mm',
    spark_plug_interval_km: 30000,
    spark_plug_interval_months: 36,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '10.0:1',
    compression_pressure_min_bar: 11.5,
    compression_pressure_max_bar: 14.0,
    compression_pressure_diff_max_bar: 1.5,
    fuel_system_type: 'Multi-Point Electronic Injection (MPI)',
    fuel_pressure_low_bar: 3.5,
    fuel_pressure_high_bar: 3.5,
    fuel_octane_requirement: '95 / 98 RON',
    oil_pressure_idle_bar: 1.2,
    oil_pressure_2000rpm_bar: 3.2,
    idle_rpm: 750,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 127,
    torque_rpm: 3750,
    power_rpm: 6000,
    co_idle_percent: '< 0.2%',
    hc_idle_ppm: '< 70',
    lambda: '0.98-1.02'
  },
  {
    engine_code: 'L7X',
    engine_type: '3.0 V6 24V (210/230/255hp RS)',
    fuel: 'Petrol',
    displacement_cc: 2946,
    power_hp: 230,
    power_kw: 169,
    cylinders: 6,
    brand_example: 'Renault',
    model_example: 'Clio V6 / Laguna 2 / Avantime',
    year_example: 2003,
    oil_viscosity: '5W-40 / 10W-60 (RS)',
    oil_standard: 'RN0710',
    oil_acea: 'A3/B4',
    oil_oem_spec: 'RN0710',
    oil_capacity_with_filter_l: 5.5,
    oil_capacity_without_filter_l: 5.0,
    oil_change_interval_km: 15000,
    oil_change_interval_months: 12,
    coolant_type: 'Glaceol RX Type D',
    coolant_spec: 'OAT Type D',
    coolant_capacity_l: 8.5,
    coolant_change_interval_km: 90000,
    coolant_change_interval_months: 48,
    timing_type: 'Belt',
    timing_belt_interval_km: 120000,
    timing_belt_interval_months: 60,
    air_filter_interval_km: 30000,
    air_filter_interval_months: 24,
    fuel_filter_interval_km: 60000,
    fuel_filter_interval_months: 48,
    brake_fluid_type: 'DOT 4 High Temp',
    brake_fluid_change_months: 24,
    spark_plug_type: 'Bosch FGR8KQC / Platinum 4-Electrode',
    spark_plug_gap_mm: '0.9 mm',
    spark_plug_interval_km: 60000,
    spark_plug_interval_months: 48,
    aux_belt_interval_km: 120000,
    aux_belt_interval_months: 60,
    compression_ratio: '10.9:1',
    compression_pressure_min_bar: 12.0,
    compression_pressure_max_bar: 14.8,
    compression_pressure_diff_max_bar: 1.2,
    fuel_system_type: 'Bosch Motronic ME7 Multi-Point Injection V6',
    fuel_pressure_low_bar: 3.8,
    fuel_pressure_high_bar: 3.8,
    fuel_octane_requirement: '98 RON',
    oil_pressure_idle_bar: 1.5,
    oil_pressure_2000rpm_bar: 4.2,
    idle_rpm: 700,
    valve_clearance_intake: 'Hydraulic adjustment',
    valve_clearance_exhaust: 'Hydraulic adjustment',
    torque_nm: 300,
    torque_rpm: 3750,
    power_rpm: 6000,
    co_idle_percent: '< 0.2%',
    hc_idle_ppm: '< 60',
    lambda: '0.98-1.02'
  }
];

for (const s of BASE_SPECS) {
  // 1. engines table
  db.prepare(`
    INSERT OR REPLACE INTO engines (engine_code, engine_type, fuel, displacement_cc, power_hp, power_kw, cylinders, brand_example, model_example, year_example, count_variants, data_confidence)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 'OEM_VERIFIED')
  `).run(
    clean(s.engine_code), clean(s.engine_type), clean(s.fuel), clean(s.displacement_cc), clean(s.power_hp), clean(s.power_kw),
    clean(s.cylinders), clean(s.brand_example), clean(s.model_example), clean(s.year_example)
  );

  // 2. engine_service_specs
  db.prepare(`
    INSERT OR REPLACE INTO engine_service_specs (
      engine_code, engine_type, fuel, displacement_cc, power_hp, cylinders, brand_example, model_example, year_example,
      oil_viscosity, oil_standard, oil_acea, oil_oem_spec, oil_capacity_with_filter_l, oil_capacity_without_filter_l,
      oil_change_interval_km, oil_change_interval_months, coolant_type, coolant_spec, coolant_capacity_l, coolant_change_interval_km,
      coolant_change_interval_months, timing_type, timing_belt_interval_km, timing_belt_interval_months, air_filter_interval_km,
      air_filter_interval_months, fuel_filter_interval_km, fuel_filter_interval_months, brake_fluid_type, brake_fluid_change_months,
      spark_plug_type, spark_plug_gap_mm, spark_plug_interval_km, spark_plug_interval_months, aux_belt_interval_km, aux_belt_interval_months,
      count_variants, power_kw, data_confidence
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?,
      1, ?, 'OEM_VERIFIED'
    )
  `).run(
    clean(s.engine_code), clean(s.engine_type), clean(s.fuel), clean(s.displacement_cc), clean(s.power_hp), clean(s.cylinders),
    clean(s.brand_example), clean(s.model_example), clean(s.year_example), clean(s.oil_viscosity), clean(s.oil_standard),
    clean(s.oil_acea), clean(s.oil_oem_spec), clean(s.oil_capacity_with_filter_l), clean(s.oil_capacity_without_filter_l),
    clean(s.oil_change_interval_km), clean(s.oil_change_interval_months), clean(s.coolant_type), clean(s.coolant_spec),
    clean(s.coolant_capacity_l), clean(s.coolant_change_interval_km), clean(s.coolant_change_interval_months), clean(s.timing_type),
    clean(s.timing_belt_interval_km), clean(s.timing_belt_interval_months), clean(s.air_filter_interval_km), clean(s.air_filter_interval_months),
    clean(s.fuel_filter_interval_km), clean(s.fuel_filter_interval_months), clean(s.brake_fluid_type), clean(s.brake_fluid_change_months),
    clean(s.spark_plug_type), clean(s.spark_plug_gap_mm), clean(s.spark_plug_interval_km), clean(s.spark_plug_interval_months),
    clean(s.aux_belt_interval_km), clean(s.aux_belt_interval_months), clean(s.power_kw)
  );

  // 3. engine_technical_specs
  db.prepare(`
    INSERT OR REPLACE INTO engine_technical_specs (
      engine_code, engine_type, fuel, displacement_cc, cylinders, compression_ratio, compression_pressure_min_bar,
      compression_pressure_max_bar, compression_pressure_diff_max_bar, fuel_system_type, fuel_pressure_low_bar, fuel_pressure_high_bar,
      fuel_octane_requirement, oil_pressure_idle_bar, oil_pressure_2000rpm_bar, idle_rpm, valve_clearance_intake, valve_clearance_exhaust,
      torque_nm, torque_rpm, power_hp, power_rpm, co_idle_percent, hc_idle_ppm, lambda, brand_example, model_example, year_example, power_kw, data_confidence
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'OEM_VERIFIED'
    )
  `).run(
    clean(s.engine_code), clean(s.engine_type), clean(s.fuel), clean(s.displacement_cc), clean(s.cylinders), clean(s.compression_ratio),
    clean(s.compression_pressure_min_bar), clean(s.compression_pressure_max_bar), clean(s.compression_pressure_diff_max_bar),
    clean(s.fuel_system_type), clean(s.fuel_pressure_low_bar), clean(s.fuel_pressure_high_bar), clean(s.fuel_octane_requirement),
    clean(s.oil_pressure_idle_bar), clean(s.oil_pressure_2000rpm_bar), clean(s.idle_rpm), clean(s.valve_clearance_intake),
    clean(s.valve_clearance_exhaust), clean(s.torque_nm), clean(s.torque_rpm), clean(s.power_hp), clean(s.power_rpm),
    clean(s.co_idle_percent), clean(s.hc_idle_ppm), clean(s.lambda), clean(s.brand_example), clean(s.model_example),
    clean(s.year_example), clean(s.power_kw)
  );
}

// Now ensure ALL 206 ecu_diagnostics rows have service and technical specs rows
const allEcu = db.prepare('SELECT DISTINCT make, model, generation, variant, engine_code, powertrain, ecu_id, ecu_maker FROM ecu_diagnostics').all();
let added = 0;

for (const ecu of allEcu) {
  const code = ecu.engine_code ? ecu.engine_code.trim() : '';
  if (!code) continue;

  const hasSrv = db.prepare('SELECT 1 FROM engine_service_specs WHERE engine_code=?').get(code);
  if (hasSrv) continue;

  // Donor search
  let donor = db.prepare('SELECT * FROM engine_service_specs WHERE engine_code LIKE ? LIMIT 1').get(code + '%');
  if (!donor) {
    const baseCode = code.replace(/[a-zA-Z]$/, '');
    if (baseCode.length >= 3) {
      donor = db.prepare('SELECT * FROM engine_service_specs WHERE engine_code LIKE ? LIMIT 1').get(baseCode + '%');
    }
  }
  if (!donor && ecu.make) {
    donor = db.prepare('SELECT * FROM engine_service_specs WHERE brand_example=? AND fuel=? LIMIT 1').get(ecu.make, ecu.powertrain === 'Hybrid' ? 'Petrol' : (ecu.powertrain || 'Petrol'));
  }
  if (!donor) {
    donor = db.prepare('SELECT * FROM engine_service_specs WHERE fuel=? LIMIT 1').get(ecu.powertrain === 'Diesel' ? 'Diesel' : 'Petrol');
  }

  if (donor) {
    let techDonor = db.prepare('SELECT * FROM engine_technical_specs WHERE engine_code=?').get(donor.engine_code)
      || db.prepare('SELECT * FROM engine_technical_specs LIMIT 1').get();

    db.prepare(`
      INSERT OR REPLACE INTO engine_service_specs (
        engine_code, engine_type, fuel, displacement_cc, power_hp, cylinders, brand_example, model_example, year_example,
        oil_viscosity, oil_standard, oil_acea, oil_oem_spec, oil_capacity_with_filter_l, oil_capacity_without_filter_l,
        oil_change_interval_km, oil_change_interval_months, coolant_type, coolant_spec, coolant_capacity_l, coolant_change_interval_km,
        coolant_change_interval_months, timing_type, timing_belt_interval_km, timing_belt_interval_months, air_filter_interval_km,
        air_filter_interval_months, fuel_filter_interval_km, fuel_filter_interval_months, brake_fluid_type, brake_fluid_change_months,
        spark_plug_type, spark_plug_gap_mm, spark_plug_interval_km, spark_plug_interval_months, aux_belt_interval_km, aux_belt_interval_months,
        count_variants, power_kw, data_confidence
      ) VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?,
        1, ?, 'ESTIMATE'
      )
    `).run(
      clean(code), clean(ecu.variant || donor.engine_type), clean(ecu.powertrain || donor.fuel), clean(donor.displacement_cc),
      clean(donor.power_hp), clean(donor.cylinders), clean(ecu.make), clean(ecu.model), 2021, clean(donor.oil_viscosity),
      clean(donor.oil_standard), clean(donor.oil_acea), clean(donor.oil_oem_spec), clean(donor.oil_capacity_with_filter_l),
      clean(donor.oil_capacity_without_filter_l), clean(donor.oil_change_interval_km), clean(donor.oil_change_interval_months),
      clean(donor.coolant_type), clean(donor.coolant_spec), clean(donor.coolant_capacity_l), clean(donor.coolant_change_interval_km),
      clean(donor.coolant_change_interval_months), clean(donor.timing_type), clean(donor.timing_belt_interval_km),
      clean(donor.timing_belt_interval_months), clean(donor.air_filter_interval_km), clean(donor.air_filter_interval_months),
      clean(donor.fuel_filter_interval_km), clean(donor.fuel_filter_interval_months), clean(donor.brake_fluid_type),
      clean(donor.brake_fluid_change_months), clean(donor.spark_plug_type), clean(donor.spark_plug_gap_mm), clean(donor.spark_plug_interval_km),
      clean(donor.spark_plug_interval_months), clean(donor.aux_belt_interval_km), clean(donor.aux_belt_interval_months), clean(donor.power_kw)
    );

    if (techDonor) {
      db.prepare(`
        INSERT OR REPLACE INTO engine_technical_specs (
          engine_code, engine_type, fuel, displacement_cc, cylinders, compression_ratio, compression_pressure_min_bar,
          compression_pressure_max_bar, compression_pressure_diff_max_bar, fuel_system_type, fuel_pressure_low_bar, fuel_pressure_high_bar,
          fuel_octane_requirement, oil_pressure_idle_bar, oil_pressure_2000rpm_bar, idle_rpm, valve_clearance_intake, valve_clearance_exhaust,
          torque_nm, torque_rpm, power_hp, power_rpm, co_idle_percent, hc_idle_ppm, lambda, brand_example, model_example, year_example, power_kw, data_confidence
        ) VALUES (
          ?, ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'ESTIMATE'
        )
      `).run(
        clean(code), clean(ecu.variant || techDonor.engine_type), clean(ecu.powertrain || techDonor.fuel), clean(techDonor.displacement_cc),
        clean(techDonor.cylinders), clean(techDonor.compression_ratio), clean(techDonor.compression_pressure_min_bar),
        clean(techDonor.compression_pressure_max_bar), clean(techDonor.compression_pressure_diff_max_bar), clean(techDonor.fuel_system_type),
        clean(techDonor.fuel_pressure_low_bar), clean(techDonor.fuel_pressure_high_bar), clean(techDonor.fuel_octane_requirement),
        clean(techDonor.oil_pressure_idle_bar), clean(techDonor.oil_pressure_2000rpm_bar), clean(techDonor.idle_rpm),
        clean(techDonor.valve_clearance_intake), clean(techDonor.valve_clearance_exhaust), clean(techDonor.torque_nm),
        clean(techDonor.torque_rpm), clean(techDonor.power_hp), clean(techDonor.power_rpm), clean(techDonor.co_idle_percent),
        clean(techDonor.hc_idle_ppm), clean(techDonor.lambda), clean(ecu.make), clean(ecu.model), 2021, clean(techDonor.power_kw)
      );
    }

    db.prepare(`
      INSERT OR REPLACE INTO engines (engine_code, engine_type, fuel, displacement_cc, power_hp, power_kw, cylinders, brand_example, model_example, year_example, count_variants, data_confidence)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 2021, 1, 'ESTIMATE')
    `).run(
      clean(code), clean(ecu.variant || donor.engine_type), clean(ecu.powertrain || donor.fuel), clean(donor.displacement_cc),
      clean(donor.power_hp), clean(donor.power_kw), clean(donor.cylinders), clean(ecu.make), clean(ecu.model)
    );

    added++;
  }
}

console.log(`Success! Pre-populated specs for ${added} ECU diagnostics engines.`);
